[tool.protobuf-to-pydantic.format]
black = true
isort = true
autoflake = true

[tool.black]
line-length = 120
target-version = ['py37', 'py38', 'py39', 'py310']


[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120

[tool.autoflake]
in-place = true
remove-all-unused-imports = true
remove-unused-variables = true
